 Exercise 1 : Array Creation and Manipulation

Create a 1D NumPy array containing numbers from 0 to 9.

In [7]:
import numpy as np

In [10]:
array_d1 = np.arange(1, 10)
print(f"array: ", array_d1)

array:  [1 2 3 4 5 6 7 8 9]


Exercise 2 : Type Conversion and Array Operations

In [15]:
array_list = np.array ([3.14, 2.17, 0, 1, 2], dtype = int)
print(f"array :" , array_list)

array : [3 2 0 1 2]


Exercise 3 : Working with Multi-Dimensional Arrays

In [19]:
array_2d = np.arange(1, 10).reshape(3, 3)
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [25]:
array_D2 = np.random.rand(4, 5)
print(f"array: ", array_D2)

array:  [[0.13327592 0.59636129 0.08765378 0.401264   0.02660934]
 [0.4109426  0.16573366 0.77077314 0.61789687 0.7526605 ]
 [0.82663026 0.68885499 0.52033899 0.04222285 0.94638669]
 [0.4273192  0.30747613 0.77884667 0.10238691 0.6629574 ]]


Exercise 5 : Indexing Arrays

In [29]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1])

[20 21 22 23 24]


Exercise 6 : Reversing elements

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [32]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_array = array[::-1]
print(f"array: ", reversed_array)

array:  [9 8 7 6 5 4 3 2 1 0]


Exercise 7 : Identity Matrix

Create a 4x4 identity matrix using NumPy.

In [34]:
array_matrix = np.eye(4)
print(array_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercise 8 : Simple Aggregate Funcs

Find the sum and average of a given 1D array.

In [39]:
array = np.array([10, 20, 30, 40, 50])
sum_array = np.sum(array)

In [42]:
print(f"Sum: " , sum_array)

Sum:  150


In [43]:
avg_array = np.mean(array)
print(f"Average: " , avg_array)

Average:  30.0


Exercise 9 : Create Array and Change its Structure

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [45]:
array_20 = np.arange(1, 21).reshape(4,5)
print(" array : ", array_20)

 array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values

Extract all odd numbers from a given NumPy array.

In [46]:
array_10 = np.arange(1,11)
print(array_10)

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
array_odd_number  = array_10 [array_10 %2 != 0]
print("odd number is : ", array_odd_number)

odd number is :  [1 3 5 7 9]
