Author : Clara Martinez

**Exercice : Understanding Numpy Arrays**

Partie 1

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.0'

In [ ]:
array_1d = np.arange(1, 6)  # 1D array from 1 to 5
array_2d = np.arange(1, 7).reshape(2, 3)  # 2D array from 1 to 6 reshaped to (2,3)

In [4]:
array_1d

array([1, 2, 3, 4, 5])

In [5]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print("Shape:", array_1d.shape, "Size:", array_1d.size, "Data Type:", array_1d.dtype)

Shape: (5,) Size: 5 Data Type: int32


In [8]:
print("Shape:", array_2d.shape, "Size:", array_2d.size, "Data Type:", array_2d.dtype)

Shape: (2, 3) Size: 6 Data Type: int32


In [9]:
array_float = np.array([1, 2, 3], dtype=float)

In [10]:
array_float

array([1., 2., 3.])

In [11]:
array_float.dtype

dtype('float64')

Partie 2

In [15]:
temperature = np.array([10,8,7,11,12,13,15])

In [16]:
temperature

array([10,  8,  7, 11, 12, 13, 15])

In [14]:
array_2d = np.array([[3, 7, 1, 9, 6], 
                      [5, 8, 2, 4, 10]])

In [17]:
array_2d

array([[ 3,  7,  1,  9,  6],
       [ 5,  8,  2,  4, 10]])

In [23]:
array_2d = np.random.randint(1, 11, size=(2, 5))

In [24]:
array_2d

array([[ 2,  8,  9,  4,  4],
       [ 5, 10,  6,  1,  4]])

Exemple image en couleur 3D

Les valeurs des pixels dans une image en niveaux de gris ou en couleur RVB (Rouge, Vert, Bleu) vont généralement de 0 à 255.

0 = Noir (absence de lumière)

255 = Blanc (lumière maximale)

Entre 0 et 255 = différentes intensités de couleur

En couleurs, un pixel est représenté par trois valeurs (R, V, B) allant de 0 à 255

In [33]:
pixel_r = np.array([255, 0, 0], dtype=np.uint8)  # Rouge pur
print("Pixel RGB:", pixel_r)

Pixel RGB: [255   0   0]


In [34]:
pixel_v = np.array([0, 250, 0], dtype=np.uint8)  # Vert pur
print("Pixel RGB:", pixel_v)

Pixel RGB: [  0 250   0]


In [26]:
image_3d = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],  # Ligne 1 (Rouge, Vert, Bleu)
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]],  # Ligne 2 (Jaune, Cyan, Magenta)
    [[100, 100, 100], [200, 200, 200], [50, 50, 50]]  # Niveaux de gris
], dtype=np.uint8)

In [27]:
image_3d

array([[[255,   0,   0],
        [  0, 255,   0],
        [  0,   0, 255]],

       [[255, 255,   0],
        [  0, 255, 255],
        [255,   0, 255]],

       [[100, 100, 100],
        [200, 200, 200],
        [ 50,  50,  50]]], dtype=uint8)

In [35]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [37]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

In [38]:
a

array([0, 1, 2])

In [39]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
result

array([[0, 2, 4],
       [3, 5, 7]])

In [41]:
import numpy as np

# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b


In [42]:
a

array([[1],
       [2],
       [3]])

In [43]:
b

array([1, 2, 3])

In [44]:
result

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [45]:
# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b

array([1, 2, 3])

In [48]:
result

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [49]:
array = np.arange(1, 10)  # Array of numbers from 1 to 9

In [50]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
reshaped_array = array.reshape(3, 3)

In [52]:
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
data = np.arange(1, 101)

In [54]:
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [55]:
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each

In [56]:
data

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [57]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])

In [58]:
A

array([[1, 2],
       [3, 4]])

In [59]:
B

array([5, 6])

In [60]:
product = A.dot(B.transpose())  # Transposing B to make multiplication possible
product

array([17, 39])

Exercice Reshape

In [71]:
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [87]:
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
mat_4x3 = array_1d.reshape(4, 3)

In [74]:
mat_4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [76]:
mat_2x6 = array_1d.reshape(2, 6)
mat_2x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [78]:
transposed_matrix = mat_2x6.T
transposed_matrix

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [79]:
mat_3x4 = array_1d.reshape(3, 4)
mat_3x4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
transposed_3x4 = mat_3x4.T

In [82]:
transposed_3x4

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [83]:
reshaped_1d = transposed_3x4.reshape(-1)

In [84]:
reshaped_1d

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

Pour aller plus loin :

In [85]:
time_series_data = np.random.rand(365)

In [89]:
time_series_data

array([0.75637706, 0.79504935, 0.92257737, 0.23717417, 0.21993371,
       0.67140579, 0.6225116 , 0.0330695 , 0.66824393, 0.49871054,
       0.00530537, 0.17093216, 0.60303671, 0.77950028, 0.0592037 ,
       0.56858167, 0.56536189, 0.48836865, 0.25519315, 0.0925107 ,
       0.92526808, 0.50299137, 0.23042339, 0.36743045, 0.68482297,
       0.17261938, 0.67441919, 0.40899128, 0.22471677, 0.345311  ,
       0.20612427, 0.30103843, 0.20425812, 0.86955441, 0.65167648,
       0.74937068, 0.5292947 , 0.19741752, 0.21715391, 0.51716015,
       0.99384288, 0.33776091, 0.19292088, 0.18895118, 0.87505731,
       0.22236077, 0.65742283, 0.96114204, 0.49070195, 0.16242575,
       0.55891428, 0.30706381, 0.15121433, 0.85981403, 0.63942742,
       0.00607514, 0.46963865, 0.54790207, 0.90135583, 0.586136  ,
       0.38820953, 0.36614695, 0.31108218, 0.06731646, 0.17056446,
       0.68348264, 0.47221567, 0.77348362, 0.22273535, 0.10601297,
       0.14578412, 0.43886613, 0.73340355, 0.27648053, 0.74914

In [86]:
reshaped_for_analysis = time_series_data[:364].reshape(52, 7)

In [88]:
reshaped_for_analysis

array([[0.75637706, 0.79504935, 0.92257737, 0.23717417, 0.21993371,
        0.67140579, 0.6225116 ],
       [0.0330695 , 0.66824393, 0.49871054, 0.00530537, 0.17093216,
        0.60303671, 0.77950028],
       [0.0592037 , 0.56858167, 0.56536189, 0.48836865, 0.25519315,
        0.0925107 , 0.92526808],
       [0.50299137, 0.23042339, 0.36743045, 0.68482297, 0.17261938,
        0.67441919, 0.40899128],
       [0.22471677, 0.345311  , 0.20612427, 0.30103843, 0.20425812,
        0.86955441, 0.65167648],
       [0.74937068, 0.5292947 , 0.19741752, 0.21715391, 0.51716015,
        0.99384288, 0.33776091],
       [0.19292088, 0.18895118, 0.87505731, 0.22236077, 0.65742283,
        0.96114204, 0.49070195],
       [0.16242575, 0.55891428, 0.30706381, 0.15121433, 0.85981403,
        0.63942742, 0.00607514],
       [0.46963865, 0.54790207, 0.90135583, 0.586136  , 0.38820953,
        0.36614695, 0.31108218],
       [0.06731646, 0.17056446, 0.68348264, 0.47221567, 0.77348362,
        0.22273535, 0.1