In [2]:
import numpy as np

In [3]:
matrix_A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_A)

Matrix A:
 [[1 2]
 [3 4]]


In [4]:
reshaped_matrix = np.reshape(matrix_A, (4, 1))
print("Reshaped Matrix:\n", reshaped_matrix)

Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]


In [5]:
matrix_A[0, 0] = 5
print("Updated Matrix A:\n", matrix_A)

Updated Matrix A:
 [[5 2]
 [3 4]]


Exercise: Movie Ratings Analysis

In [6]:
movie_ratings = np.array([
    [5, 1, 4],
    [4, 4, 2],
    [4, 3, 5],
    [1, 1, 5],
    [3, 2, 1]
])

In [22]:
# Calculating various statistics
average_responses = np.mean(movie_ratings, axis=0)
total_responses = np.sum(movie_ratings, axis=0)
max_responses = np.max(movie_ratings, axis=0)
min_responses = np.min(movie_ratings, axis=0)

In [23]:
print("Average Responses:", average_responses)
print("Total Responses:", total_responses)
print("Maximum Responses:", max_responses)
print("Minimum Responses:", min_responses)

Average Responses: [3.4 2.2 3.4]
Total Responses: [17 11 17]
Maximum Responses: [5 4 5]
Minimum Responses: [1 1 1]


Exercises and Practice
Basic Matrix Operations Exercise

Create two 3x3 matrices in NumPy.
Perform addition, subtraction on them.
Expected Output: Display the results of these operations.

In [25]:
# Define two matrices
matrix_B = np.array([[9, 3], [9, 5]])
matrix_C = np.array([[11, 1], [3, 6]])

# Adding and subtracting matrices
sum_matrix = np.add(matrix_B, matrix_C)
diff_matrix = np.subtract(matrix_B, matrix_C)

print("Sum of Matrices:\n", sum_matrix)
print("Difference of Matrices:\n", diff_matrix)

Sum of Matrices:
 [[20  4]
 [12 11]]
Difference of Matrices:
 [[-2  2]
 [ 6 -1]]


In [26]:
# Multiplication of two matrices
prod_matrix = np.dot(matrix_B, matrix_C)
print("Product of Matrices:\n", prod_matrix)

Product of Matrices:
 [[108  27]
 [114  39]]


Calculating Variance, Skewness, and Kurtosis

In [27]:
# Random sampling from an array
data = np.arange(10)
sample = np.random.choice(data, size=5, replace=False)
print("Random Sample:", sample)

Random Sample: [8 0 7 9 4]


In [28]:
# Shuffling data
np.random.shuffle(data)
print("Shuffled Data:", data)

Shuffled Data: [3 0 7 1 8 9 5 4 6 2]


 Compute Descriptive Statistics: Calculate mean, median, variance, skewness, and kurtosis of a randomly generated dataset.

In [ ]:
# Variance
variance = np.var(samples)
print("Variance:", variance)

# Skewness and Kurtosis require scipy
from scipy.stats import skew, kurtosis
print("Skewness:", skew(samples))
print("Kurtosis:", kurtosis(samples))

Exercises on Time Series Data in NumPy
1. Data Creation Exercise:

Objective: Create a simulated time series dataset.

Generate a date range from January 1, 2022, to December 31, 2022, with a daily frequency.

In [32]:
# Creating date ranges
dates = np.arange('2022-01', '2022-12', dtype='datetime64[D]' )
print("Years 2022 Dates:\n", dates)

Years 2022 Dates:
 ['2022-01-01' '2022-01-02' '2022-01-03' '2022-01-04' '2022-01-05'
 '2022-01-06' '2022-01-07' '2022-01-08' '2022-01-09' '2022-01-10'
 '2022-01-11' '2022-01-12' '2022-01-13' '2022-01-14' '2022-01-15'
 '2022-01-16' '2022-01-17' '2022-01-18' '2022-01-19' '2022-01-20'
 '2022-01-21' '2022-01-22' '2022-01-23' '2022-01-24' '2022-01-25'
 '2022-01-26' '2022-01-27' '2022-01-28' '2022-01-29' '2022-01-30'
 '2022-01-31' '2022-02-01' '2022-02-02' '2022-02-03' '2022-02-04'
 '2022-02-05' '2022-02-06' '2022-02-07' '2022-02-08' '2022-02-09'
 '2022-02-10' '2022-02-11' '2022-02-12' '2022-02-13' '2022-02-14'
 '2022-02-15' '2022-02-16' '2022-02-17' '2022-02-18' '2022-02-19'
 '2022-02-20' '2022-02-21' '2022-02-22' '2022-02-23' '2022-02-24'
 '2022-02-25' '2022-02-26' '2022-02-27' '2022-02-28' '2022-03-01'
 '2022-03-02' '2022-03-03' '2022-03-04' '2022-03-05' '2022-03-06'
 '2022-03-07' '2022-03-08' '2022-03-09' '2022-03-10' '2022-03-11'
 '2022-03-12' '2022-03-13' '2022-03-14' '2022-03-15' '202

Simulate daily temperature data for this period. Assume temperature varies between 10°C and 35°C.
Simulate daily humidity data for the same period. Assume humidity varies between 30% and 90%.
Structure the data into a DataFrame with columns: Date, Temperature, and Humidity.